NEW: Функционал получения аргументов команжной строки из переменных окружения+ тесты
oscript-library/cmdline pull request #4
Opened 2017-06-15 08:23 UTC by Khorevaa

Реализовал базовый функционал 
Тесты сложных случаев.

2017-06-15 08:24 UTC, Khorevaa commented
/cc @artbear  @nixel2007  @EvilBeaver

2017-06-15 08:34 UTC, dmpas commented on packagedef
> +    .ЗависитОт("logos")
пробелотабы

2017-06-15 08:59 UTC, artbear commented on tests/cmdline-test.os
> +КореньКоманды = ПолучитьПеременнуюСреды(ВРег("cmdline_command_prefix"));
Перевод строки добавь, плиз.

2017-06-15 09:04 UTC, artbear requested changes
Нужный PR, 
мы что-то подобное делали в vanessa-runner, но не слишком универсально.

Мне пока что не нравятся магические имена `cmdline_command_prefix` и т.п.
Нужно от них избавиться.

Например, если они нужны, тогда явно возвращать их имена спец.методом (или методами) парсера.

2017-06-15 09:08 UTC, artbear commented on src/cmdline.os
> +Процедура ИспользоватьПеременныеОкружения(Знач ЛокальныйПрефикс = Неопределено, Знач КореньКоманды = Неопределено) Экспорт
Еще желательно отделить экспортный метод от приватных методов для лучшей структуры кода.

Новые приватные методы убрать в конец модуля, как сделано сейчас для других подобных методов

2017-06-15 09:11 UTC, artbear commented on tests/cmdline-test.os
> +КореньКоманды = ПолучитьПеременнуюСреды(ВРег("cmdline_command_prefix"));
@Khorevaa Поясни, пожалуйста, назначение глобального и локального префиксов.
Зачем нужны именно два префикса, когда вполне можно обойтись одним, как в vanessa-runner ?

2017-06-15 09:13 UTC, artbear commented on tests/cmdline-test.os
> +КореньКоманды = ПолучитьПеременнуюСреды(ВРег("cmdline_command_prefix"));
Ну и соответственно, зачем нужен еще один префикс `КореньКоманды` ?

2017-06-15 09:16 UTC, artbear commented on tests/cmdline-test.os
> +	ПарсерКомаднойСтроки.ДобавитьПараметрКоллекция("list", "список параметров");
В обоих тест.сценариях не увидел тест для параметра-флага (глобальный и для команды)

2017-06-15 09:17 UTC, Khorevaa commented on tests/cmdline-test.os
> +КореньКоманды = ПолучитьПеременнуюСреды(ВРег("cmdline_command_prefix"));
Глобальный устанавливается только через переменную окружения например, для сервер сборок Bamboo его добавляет сам. 
Локальный же может определять разработчик при подключении функцональности в приложение

2017-06-15 09:17 UTC, Khorevaa commented on tests/cmdline-test.os
> +КореньКоманды = ПолучитьПеременнуюСреды(ВРег("cmdline_command_prefix"));
Пример, BAMBOO_GITSYNC_*

2017-06-15 09:18 UTC, Khorevaa commented on tests/cmdline-test.os
> +	ПарсерКомаднойСтроки.ДобавитьПараметрКоллекция("list", "список параметров");
Да косяк...

2017-06-15 09:33 UTC, Khorevaa commented on src/cmdline.os
> +Процедура ИспользоватьПеременныеОкружения(Знач ЛокальныйПрефикс = Неопределено, Знач КореньКоманды = Неопределено) Экспорт
Убрал в конец.

2017-06-15 09:33 UTC, Khorevaa commented on tests/cmdline-test.os
> +КореньКоманды = ПолучитьПеременнуюСреды(ВРег("cmdline_command_prefix"));
Добавил

2017-06-15 09:33 UTC, artbear commented
Предлагаю добавить в парсер 2 метода
+ `Функция ПолучитьПрефиксыПеременныхСреды()`
  + возвращается структура с 3 ключами - `Глобальный`, `Локальный`, `Команда` и магическими именами их полей.
+ `Процедура УстановитьПрефиксыПеременныхСреды(НовыеЗначения)`
  + принимает структуру из 1го метода и устанавливает новые магические имена полей 

и вместо кода со смешением стилей (рус-англ) и магическими строками
```bsl
УстановитьПеременнуюСреды(ВРег("cmdline_prefix"), "TEST_");
УстановитьПеременнуюСреды(ВРег("cmdline_global_prefix"), "OS");
УстановитьПеременнуюСреды(ВРег("cmdline_command_prefix"), "COMMAND");

ЛокальныйПрефикс = ПолучитьПеременнуюСреды(ВРег("cmdline_prefix"));
ГлобальныйПрефикс = ПолучитьПеременнуюСреды(ВРег("cmdline_global_prefix"));
КореньКоманды = ПолучитьПеременнуюСреды(ВРег("cmdline_command_prefix"));
```
используем красивый и простой код
```bsl
ПарсерКомаднойСтроки = Новый ПарсерАргументовКоманднойСтроки;
ИменаПрефиксов = ПарсерКомаднойСтроки.ПолучитьПрефиксыПеременныхСреды();

УстановитьПеременнуюСреды(ИменаПрефиксов.Локальный, "TEST_");
УстановитьПеременнуюСреды(ИменаПрефиксов.Глобальный, "OS");
УстановитьПеременнуюСреды(ИменаПрефиксов.Команда, "COMMAND");

ЛокальныйПрефикс = ПолучитьПеременнуюСреды(ИменаПрефиксов.Локальный);
ГлобальныйПрефикс = ПолучитьПеременнуюСреды(ИменаПрефиксов.Глобальный);
КореньКоманды = ПолучитьПеременнуюСреды(ИменаПрефиксов.Команда);
```

2017-06-15 09:33 UTC, Khorevaa commented on packagedef
> +    .ЗависитОт("logos")
Поправил

2017-06-15 09:36 UTC, artbear commented on tests/cmdline-test.os
> +	ПарсерКомаднойСтроки.ДобавитьПараметрКоллекция("list", "список параметров");
В `ТестДолжен_ПрочитатьПараметрыКомандыИзПеременныхСреды` также не хватает проверки глобального позиционного параметра

2017-06-15 09:38 UTC, artbear commented on tests/cmdline-test.os
> +КореньКоманды = ПолучитьПеременнуюСреды(ВРег("cmdline_command_prefix"));
По глобальному и локальному префиксу хорошее пояснение.
Да, бамбу так делает. у ТимСити также что-то подобное есть.

Хорошо бы это пояснение вставить в код парсера для большего пояснения и в ридми

2017-06-15 09:40 UTC, Khorevaa commented
Как вариант. Но смысл был в том чтобы можно было определить префиксы в приложении не устанавливая переменные среды. 

```bsl
ПарсерКомаднойСтроки = Новый ПарсерАргументовКоманднойСтроки;
ПарсерКомаднойСтроки.ИспользоватьПеременныеОкружения("gitsync_");
```
Магические префиксы ввел как альтернативая, при использовании на серверах сборки
При этом установленные чере процедуру перекрывают "магические" переменные окрыжения

2017-06-15 09:48 UTC, artbear commented
Кстати, у тебя нет тестов на проверку `ПарсерКомаднойСтроки.ИспользоватьПеременныеОкружения("Значение");` :(

2017-06-15 09:49 UTC, Khorevaa commented
Кстати да...

2017-06-15 09:50 UTC, artbear commented
>Но смысл был в том чтобы можно было определить префиксы в приложении не устанавливая переменные среды.
```bsl
ПарсерКомаднойСтроки = Новый ПарсерАргументовКоманднойСтроки;
ПарсерКомаднойСтроки.ИспользоватьПеременныеОкружения("gitsync_");
```

Сделай простой тест-пример работы как в реальном приложении, аналогичный этому коду.
с использованием и глобального и локального префикса.

Хочется понять, придется ли нам юзать магические имена или нет.

2017-06-15 09:51 UTC, Khorevaa commented
Если надо установить глобальный префикс то надо будет заюзать магическое имя.. без этого никак.

2017-06-15 09:56 UTC, artbear commented on src/cmdline.os
> +	КореньКоманды = ПолучитьПеременнуюСреды(Стандартная_ПрефиксКомандыПеременнаяОкружения);
Еще мне не понятно, зачем получать корень команды, локальный и глобальный префиксы из переменных среды.

2017-06-15 09:56 UTC, artbear commented
Поэтому я и предлагаю сделать тест-пример работы как в реальном приложении

Сразу многое станет проще и понятнее.

2017-06-15 09:57 UTC, artbear commented
Например, как будто тест работает из под Бамбу.

2017-06-15 09:58 UTC, artbear commented
Или для ванесса-раннер, у которой есть локальный префикс `RUNNER_`

2017-06-15 10:00 UTC, artbear commented
кстати, в ванесса-раннер юзается код
`СоответствиеПеременных.Вставить("RUNNER_IBNAME", "--ibname");`

предлагаю входные `--` просто убирать из имена параметров перед анализом переменных среды

2017-06-15 10:05 UTC, artbear commented on src/cmdline.os
> +	ОбщийПрефикс = СтрШаблон("%1%2", ПрефиксыПеременныхОкружения.ГлобальныйПрефикс, ПрефиксыПеременныхОкружения.ЛокальныйПрефикс);
Не нравится дублирование имен
`ПрефиксыПеременныхОкружения.ГлобальныйПрефикс` 
`ПрефиксыПеременныхОкружения.ЛокальныйПрефикс`

как я уже писал выше - предлагаю простое Глобальный, Локальный, Команда

2017-06-15 10:06 UTC, artbear commented
>Если надо установить глобальный префикс то надо будет заюзать магическое имя.. без этого никак.

вот тут нам и пригодятся методы ПолучитьИменаПрефиксов и УстановитьИменаПрефиксов

2017-06-15 10:08 UTC, Khorevaa commented
> вот тут нам и пригодятся методы ПолучитьИменаПрефиксов и УстановитьИменаПрефиксов
Как раз это и не пригодится т.к. это делается ГЛОБАЛЬНО и в приложении не вызывается т.к. нет смысла затачивать приложение под определенный сервер сборок

2017-06-15 10:09 UTC, artbear commented
ты сам написал `Если надо установить глобальный префикс `, а я тебе дал ответ на это :)

2017-06-15 10:13 UTC, artbear commented
В общем, жду 

>Поэтому я и предлагаю сделать тест-пример работы как в реальном приложении
> + Например, как будто тест работает из под Бамбу.
> + Или для ванесса-раннер, у которой есть локальный префикс RUNNER_
>
>Сразу многое станет проще и понятнее.

2017-06-15 10:14 UTC, Khorevaa commented on tests/cmdline-test.os
> +	ПарсерКомаднойСтроки.ДобавитьПараметрКоллекция("list", "список параметров");
А нет такой возможности в принципе установки глобального позиционного параметра

2017-06-15 10:15 UTC, Khorevaa commented on tests/cmdline-test.os
> +	ПарсерКомаднойСтроки.ДобавитьПараметрКоллекция("list", "список параметров");
Хотя нашел

2017-06-15 11:17 UTC, Khorevaa commented on src/cmdline.os
> +	ОбщийПрефикс = СтрШаблон("%1%2", ПрефиксыПеременныхОкружения.ГлобальныйПрефикс, ПрефиксыПеременныхОкружения.ЛокальныйПрефикс);
Сделал короткие именя

2017-06-15 11:22 UTC, Khorevaa commented
Пример в тесте ТестДолжен_ДолженПроверитьРаботуНаСерверСборокИзПеременныхСреды

2017-06-15 11:23 UTC, Khorevaa commented on tests/cmdline-test.os
> +	ПарсерКомаднойСтроки.ДобавитьПараметрКоллекция("list", "список параметров");
Помоги найти глобальные позиционные параметры не нахожу..

2017-06-15 11:25 UTC, artbear commented
По глобальным позиционным параметрам смотри метод `ДобавитьПараметр`

2017-06-15 11:28 UTC, Khorevaa commented
> По глобальным позиционным параметрам смотри метод ДобавитьПараметр
Посмотрел он не устанавливает позиционные глобальные параметры

2017-06-15 11:34 UTC, artbear commented
Ну как же не устанавливает-то ?
Там даже в коде используются `мПозиционныеПараметры`
```bsl
Функция ДобавитьПараметр(Знач ИмяПараметра, Знач Пояснение = "") Экспорт
	
	Лог.Отладка("ДобавитьПараметр: ИмяПараметра <"+ИмяПараметра+">");		
	
	ДобавитьПараметрВТаблицу(мПозиционныеПараметры, ИмяПараметра, Пояснение, Ложь, Ложь);
	
КонецФункции

Функция ДобавитьИменованныйПараметр(Знач ИмяПараметра, Знач Пояснение = "", Знач Глобальный = Ложь) Экспорт
	
	Лог.Отладка("ДобавитьИменованныйПараметр: ИмяПараметра <"+ИмяПараметра+">");		
	
	ДобавитьПараметрВТаблицу(мПараметры, ИмяПараметра, Пояснение, Ложь, Глобальный);
	
КонецФункции

```

2017-06-15 11:35 UTC, Khorevaa commented
Глобальность не определяет его. 

```bsl
ДобавитьПараметрВТаблицу(мПозиционныеПараметры, ИмяПараметра, Пояснение, Ложь, **Ложь)**;

```

2017-06-15 11:38 UTC, Khorevaa commented
```bsl
Функция РазобратьКоманду(Знач МассивПараметров) Экспорт
	
	Если МассивПараметров.Количество() = 0 Тогда
		Возврат Неопределено;
	КонецЕсли;
	
	ОписаниеКоманды = мКоманды[МассивПараметров[0]];
	Если ОписаниеКоманды = Неопределено Тогда
		ВызватьИсключение "Неизвестная команда: " + МассивПараметров[0];
	КонецЕсли;
	Лог.Отладка("Разбор команды: " + ОписаниеКоманды.Команда);
	
	ГлобальныеПараметры = мПараметры.НайтиСтроки(Новый Структура("ЭтоГлобальныйПараметр", Истина));
	Для Каждого СтрГлобальныйПараметр Из ГлобальныеПараметры Цикл
		СтрСуществующий = ОписаниеКоманды.ИменованныеПараметры.Найти(СтрГлобальныйПараметр.Имя,"Имя");
		Если СтрСуществующий = Неопределено Тогда
			Лог.Отладка("Добавляю глобальный параметр: " + СтрГлобальныйПараметр.Имя);
			ЗаполнитьЗначенияСвойств(ОписаниеКоманды.ИменованныеПараметры.Добавить(), СтрГлобальныйПараметр,, "ЭтоГлобальныйПараметр");
		КонецЕсли;
	КонецЦикла;
	
	РезультатКоманды = Новый Структура;
	РезультатКоманды.Вставить("Команда", ОписаниеКоманды.Команда);
	РезультатКоманды.Вставить("ЗначенияПараметров", Новый Соответствие);
	
	мМассивВходныхПараметров = МассивПараметров;
	мПозицияВСпискеТокенов = 1;
	мПозицияПозиционныхПараметров = 0;
	
	РезультатКоманды.ЗначенияПараметров = РазобратьАргументы(ОписаниеКоманды.ИменованныеПараметры, ОписаниеКоманды.ПозиционныеПараметры);
	
	Лог.Отладка("Трассировка РезультатКоманды.ЗначенияПараметров:");
	ВывестиРезультатРазбора(РезультатКоманды.ЗначенияПараметров);
	
	Возврат РезультатКоманды;
	
КонецФункции

```

Для команды используются только глобальные ИМЕННОВАННЫЕ параметры, позиционные не анализируются

2017-06-15 11:45 UTC, Khorevaa commented
> предлагаю входные -- просто убирать из имена параметров перед анализом переменных среды

Вопрос если параметры определи как 

```
--ib-name
--ib-user
--ib-password

или как краткое представление 
-i 
-u
-s
```
Убирать нужны тогда `-` и `--`?

2017-06-15 12:07 UTC, artbear commented
Пока предлагаю убирать только `--`, они практически всегда в начале параметров/команд будут

одиночный `-` убирать не всегда возможно, т.к. не всегда понятно, что делать с разделителем слов

Например, `--db-user`

2017-06-15 13:20 UTC, EvilBeaver commented
Господа, я против данного PR. Нахрена это всё? Получение параметров? Ок. Но это НЕ cmdline. Данный пакет это парсер аргументов. Хотите абстрактный получатель параметров - это другой пакет. И у него на входе могут быть аргументы или окружение или файл. Но не в cmdline

2017-06-15 14:01 UTC, Khorevaa commented
@EvilBeaver  Может ты и прав, но другого пакета нет.

2017-06-15 14:44 UTC, EvilBeaver commented
Что мешает сделать?

2017-06-15 14:45 UTC, EvilBeaver commented
Рабочее название parampampam

2017-06-15 14:49 UTC, Khorevaa commented
Так его надо начать делать сделать основу и внедрить во все приложения

2017-06-15 14:52 UTC, nixel2007 commented
> Так его надо начать делать сделать основу и внедрить во все приложения

дык @Stepa86 уже начинал делать?

2017-06-15 14:55 UTC, Khorevaa commented
@nixel2007  Так там только чтение из JSON.

2017-06-15 15:03 UTC, nixel2007 commented
@Khorevaa переменные среды вроде бы тоже были. @Stepa86?

2017-06-15 15:09 UTC, EvilBeaver commented
Все равно. Оставьте парсеру парсерово

2017-06-15 15:10 UTC, Khorevaa commented
@nixel2007 Вроде не нашел..

2017-06-15 15:11 UTC, Khorevaa commented
@EvilBeaver  - прикинул стурктуру библиотеки. Она будет повторять cmdline - парсер. Т.к. тоже потрубуется описание "команды", параметров к ней и т.д.

2017-06-15 15:13 UTC, Khorevaa commented
@EvilBeaver  Как вариант можно передавать парсер целиком и из него все это считывать

2017-06-15 18:22 UTC, Stepa86 commented
@nixel2007 В моей читалке параметров из файла только чтение из json, т.к. он удобный и понятный, и в VSC так же параметры задаются. Я хотел бахнуть и чтение всех переменных окружения в возвращаемое соответствие, но не в ближайшее время.

2017-06-16 05:40 UTC, EvilBeaver commented
@Khorevaa структура будет похожей но не совсем. Позиционность параметров характерга именно для командной строки. "Параметр" вообще, как абстрактное понятие - не позиционен. Он может иметь тип, имя и обязательность. А потом представляться в env одним образом, из cli - другим, из конфиг-файла - третьим.

2017-11-21 10:17 UTC, artbear commented
В настоящий момент я против этого PR, т.к. подобная функциональность и более расширенная (файлы настроек и т.п.) мной уже реализована в репозитории https://github.com/oscript-library/params

А cmdline останется только парсером параметров командной строки.

Params же является надстройкой над cmdline и позволяет большее управление.

2017-11-21 10:35 UTC, closed without merging